# ============ 网络 ============
bind 0.0.0.0
port 6379
timeout 300
tcp-keepalive 60
protected-mode no

# ============ 通用 ============
daemonize no
pidfile /var/run/redis_6379.pid
loglevel notice
databases 16

# ============ 密码 / 安全 ============
requirepass redis123
# 生产建议用 ACL 代替 requirepass，后面我教你升级

# ============ 持久化：RDB ============
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir /data

# ============ 持久化：AOF ============
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-load-truncated yes
aof-use-rdb-preamble yes

# ============ 内存 ============
maxmemory 2gb
maxmemory-policy allkeys-lru

# ============ 慢查询日志 ============
slowlog-log-slower-than 10000
slowlog-max-len 128

# ============ 禁用危险命令（生产习惯） ============
rename-command FLUSHALL ""
rename-command FLUSHDB ""
# KEYS 先不禁用，实验阶段方便调试